export const all: string;
export const content: string;
export const show: string;
export const subImages: string;
export const showSubImages: string;
export const imageShow: string;
export const showOneImage: string;
export const oneImage: string;
export const titleAndInfo: string;
